name: Robot Framework CI

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 12 * * 4" # Quinta-feira às 09:00 BRT (12:00 UTC)

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Allure CLI
        run: |
          ALLURE_VERSION=2.30.0
          wget https://github.com/allure-framework/allure2/releases/download/$ALLURE_VERSION/allure-$ALLURE_VERSION.zip
          unzip allure-$ALLURE_VERSION.zip -d /opt/allure
          export PATH=$PATH:/opt/allure/allure-$ALLURE_VERSION/bin
          allure --version

      - name: Create reports directories
        run: mkdir -p api/reports/api_allure

      - name: Run Robot Framework tests (if any)
        run: |
          if find ./api/tests -name "*.robot" | grep -q .; then
            echo "Executando testes Robot Framework..."
            find ./api/tests -name "*.robot" -exec robot --output=api/reports/output.xml --log=api/reports/log.html --report=api/reports/report.html --listener="allure_robotframework;api/reports/api_allure" {} +
          else
            echo "Nenhum arquivo .robot encontrado. Pulando execução."

      - name: Generate Allure HTML report
        run: |
          if [ -d "api/reports/api_allure" ] && [ "$(ls -A api/reports/api_allure)" ]; then
            /opt/allure/allure-2.30.0/bin/allure generate api/reports/api_allure -o api/reports/allure-report --clean
            ls -R api/reports/allure-report
          else
            echo "Nenhum resultado Allure para gerar. Pulando geração de relatório."

      - name: Upload Robot & Allure reports
        uses: actions/upload-artifact@v4
        with:
          name: robot-allure-reports
          path: |
            api/reports/output.xml
            api/reports/log.html
            api/reports/report.html
            api/reports/allure-report
